# Generated by Django 4.1 on 2024-06-21 22:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Amazon', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='cliente',
            name='sexo',
            field=models.CharField(choices=[('F', 'femenino'), ('M', 'masculino')], default='-', max_length=1),
        ),
    ]
