# Generated by Django 4.1 on 2024-06-22 06:06

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('Amazon', '0005_cupon_direccionenvio'),
    ]

    operations = [
        migrations.AddField(
            model_name='direccionenvio',
            name='fecha_creacion',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='direccionenvio',
            name='user',
            field=models.OneToOneField(default=6, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='direccionenvio',
            name='codigo_postal',
            field=models.CharField(max_length=5),
        ),
        migrations.AlterField(
            model_name='direccionenvio',
            name='telefono',
            field=models.CharField(max_length=9),
        ),
    ]
