# Generated by Django 4.1 on 2024-06-22 08:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Amazon', '0006_direccionenvio_fecha_creacion_direccionenvio_user_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Pago',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero_tarjeta', models.CharField(max_length=16)),
                ('fecha_expiracion', models.CharField(max_length=5)),
                ('nombre_propietario', models.CharField(max_length=100)),
                ('cvv', models.CharField(max_length=4)),
                ('guardar_tarjeta', models.BooleanField(default=False)),
                ('fecha_pago', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
